import Head from 'next/head'
import { motion } from 'framer-motion'

export default function Home() {
  return (
    <motion.div
      className="bg-purple-300 text-gray-900 absolute top-0 left-0 w-full h-full lg:px-48 px-16"
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: 'easeOut' }}
      exit={{ opacity: 1 }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-gray-500'>
        <div className="my-96 p-1">
          <motion.h1
            className="text-gray-900 text-6xl text-center lg:text-right lg:text-9xl"
            animate={{ x: 0 }}
            initial={{ x: "-100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
          >Harv Creative</motion.h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2023</h2>
          </div>

          <div>
            <h3>Contribute more than you consume.</h3>
            <h3>Filipino creative designs to satisfy your needs.</h3>
            <h3>Click me.</h3>
          </div>
        </div>
      </main>
    </motion.div>
  )
}
